### ISSUE TITLE
Printing route not working

### ISSUE THREAD

**Issue by heia-fr-maeder** [deranjer/hugo-cookbook#4]
Hi
I set up a hugo site with your template as described within your README.md 

Thanks for your great work. Unfortunately, the printing doesn't work, I get always a _I'm sorry, your recipe is in another castle..._ error page. Must something special be in the config.toml file?

**Comment by deranjer** [comment]
So sorry, haven't been tracking this.  Finally updated my version of hugo and discovered the issue, your config.toml should look like this:

```toml
# Print output just creates a special route for a print view
[outputs]
    home = ["html", "rss", "json"]
    page = ["html", "print"]

  
# The settings for the print format
[outputFormats]
  [outputFormats.print]
    name = "print"
    mediaType = "text/html"
    baseName = "print"
    isPlainText = false
    rel = "print"
    isHTML = true
    noUgly = true
    permalinkable = true
    path = "print"
```
